runner: python
install:
  artifacts: "https://raw.githubusercontent.com/Tectone23/MobileRuntime/main/config.json"
  cmd_nix:
    - "mv config.json ~/.tre-config.json"
    - "./src/main.py --headless-init"
actions:
  run_api: "--cog_path={cog_path}"
  run_interactive: "--cog_path={cog_path} --interactive"
  version: "--version"
